### PR TITLE
link to wickerson paper

### PR DESCRIPTION
**Pull request by johnwickerson**

### CODE REVIEW

**Comment by gasche** [comment]
Hi @johnwickerson . Thanks for the pull request!

Could you comment a bit on why you would prefer a link to your personal webpage instead of arXiv? Without much thinking, my personal preference would go to linking both (something like "(preprint), also on (arXiv)"). Reasons:
- against arXiv: your personal copy may be more up-to-date (it's easier to update when you make changes), but then it's possible to send a new version on arXiv (but maybe one of your co-author does the upload and you don't have easy control over it)
- for arXiv: arxiv is designed for long-term archival, so I would assume that a paper available on arxiv today will still be available ten or twenty years from now (and those preprint collections may still have value then); on the contrary, I'm less confident about github lasting that long, or you not changing your website organization in the meantime.
- for arXiv: I would like to encourage people from our community to send their work to arXiv (I think it is superior to just having a copy one's personal webpage), so I like to emphasize arXiv uploads when they exist.

None of those reasons are incompatible with having both links present and emphasizing the one you suggest. If that format would suit you, I can take care of the change myself.

**Comment by johnwickerson** [comment]
Mm, good points. Ok, I'll update the arXiv version. But if you could also give the link to my personal webpage, I think that'd be best. Thanks!

(PS. Can you make one for POPL'17 too? It's a great service you provide!)

**Comment by gasche** [comment]
Thanks! I made a [popl2017-papers](https://github.com/gasche/popl2017-papers) repo this morning, but your paper is already in -- linked from your website.

**Comment by johnwickerson** [comment]
Ah, great stuff! Thanks Gabriel.

**Pull request merged**
