### PR TITLE
Added a few links + fix error

### PR DESCRIPTION
**Pull request by atrieu**

### CODE REVIEW

**Comment by gasche** [comment]
Could you add direct links to the PDFs along with the "paper website" links? I have a very hard time figuring how to read the paper on "Breaking Through the Normalization Barrier: A Self-Interpreter for F-omega" from the link added.

**Comment by gasche** [comment]
If a paper is _not_ available from a paper website, we should mark it explicitly (for example "website (no preprint available yet)"), to avoid readers wasting their time looking for the paper. This seems to be the case for the key-value-stores article.

**Comment by atrieu** [comment]
I haven't found them actually, that's why I have only put the links for the websites.

**Comment by gasche** [comment]
Ok, I'll update the link names myself them. Thanks for the links!

**Pull request merged**
