### PR TITLE
Add an arXiv link to the "Overhauling SC atomics" paper

### PR DESCRIPTION
**Pull request by adrieng**

### CODE REVIEW

**Comment by gasche** [comment]
Would you also include a direct link to the [pdf document](http://arxiv.org/pdf/1503.07073v2)? Given that the last arxiv update is after the POPL submission deadline, I think we can assume this is close enough to a preprint to not be misleading.

**Comment by gasche** [comment]
Micro-management of pull requests does not work well for minuscule changes. I did the fix myself. Thanks!

**Comment by adrieng** [comment]
No problem. I must admit that I don't like having a direct link to a PDF file hosted on the arXiv, but YMMV.

**Comment by gasche** [comment]
Because the link will change if the authors send a revision? My reason for adding the link was to decrease the time-to-article-reading for users.

**Comment by adrieng** [comment]
Yes.

**Comment by gasche** [comment]
So the arxiv pdf URL looks like so

> http://arxiv.org/pdf/1503.07073v2

but in fact you can remove the `v2` suffix at the end

> http://arxiv.org/pdf/1503.07073

and this URL always refers to the most recent version. Win!

**Pull request merged**
