### PR TITLE
Fω Equirecursive etc project website

### PR DESCRIPTION
**Pull request by maxsnew**

### CODE REVIEW

**Comment by gasche** [comment]
@Blaisorblade , do you plan to make a preprint avaiable ? :-)

**Comment by Blaisorblade** [comment]
Yes, I'm on it :smile:

**Comment by Blaisorblade** [comment]
URL: http://ps.informatik.uni-tuebingen.de/research/functors/equirecursion-fomega-popl16.pdf (linked from the project page). Enjoy (but only infinitarily or corecursively :laughing: )!

**Comment by gasche** [comment]
Thanks! I added the link.

**Pull request merged**
